-- drop table users;
create table users
(
    id       number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name     varchar2(255)        not null,
    email    varchar2(255) unique not null,
    password varchar2(255)        not null
);

create table genders
(
    id   number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name varchar2(255) not null
);

-- drop table patients;
create table patients
(
    id         number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    user_id    number(20, 0) not null references users (id),
    first_name varchar2(255) not null,
    last_name  varchar2(255) not null,
    patronymic varchar2(255) null,
    birthdate  date          not null,
    gender_id  number(20, 0) not null references genders (id),
    phone      number(20, 0) null,
    area       varchar2(255) not null
);

-- drop table patient_documents;
create table patient_documents
(
    id         number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name       varchar2(255) not null,
    patient_id number(20, 0) not null references patients (id),
    content    blob          null
);

-- drop table regions;
create table regions
(
    id   number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name varchar2(255) unique not null,
    code number(3, 0) unique  not null
);

-- drop table towns;
create table towns
(
    id        number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name      varchar2(255) unique not null,
    region_id number(20, 0)        not null references regions (id)
);

-- drop table organizations;
create table organizations
(
    id      number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name    varchar2(255) not null,
    town_id number(20, 0) not null references towns (id)
);

create table hospital_types
(
    id   number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name varchar2(255) not null
);

create table week_days
(
    id   number(1, 0) primary key,
    name varchar2(255)
);

-- drop table hospitals;
create table hospitals
(
    id              number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    deleted_at      date               null,
    name            varchar2(255)      not null,
    organization_id number(20, 0)      not null references organizations (id),
    status          smallint default 0 not null,
    type_id         number(20, 0)      not null references hospital_types (id)
);

create table hospital_work_times
(
    id          number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    week_day_id number(1) references week_days (id),
    hospital_id number(20, 0) references hospitals (id),
    begin_time  number(5, 0) null,
    end_time    number(5, 0) null,

    constraint hospital_work_times_week_day_id_hospital_id_unique unique (week_day_id, hospital_id)
);

-- drop table doctors;
create table doctors
(
    id          number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    deleted_at  date          null,
    area        varchar2(255) not null,
    degree      varchar2(255) not null,
    hospital_id number(20, 0) not null references hospitals (id)
);

create table age_groups
(
    id        number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    name      varchar2(255)            null,
    age_begin number(3, 0) default 0   not null,
    age_end   number(3, 0) default 999 not null
);

-- drop table specialities;
create table specialities
(
    id           number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    deleted_at   date          null,
    age_group_id number(20, 0) not null references age_groups (id),
    gender_id       number(20, 0) not null references genders (id)
);

-- drop table doctor_specialty;
create table doctor_specialty
(
    speciality_id number(20, 0) not null references specialities (id),
    doctor_id     number(20, 0) not null references doctors (id),

    constraint speciality_id_doctor_id_unique unique (speciality_id, doctor_id)
);

-- drop table tickets;
create table tickets
(
    id         number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    doctor_id  number(20, 0)          not null references doctors (id),
    closed     number(1, 0) default 0 not null,
    time_begin date                   not null,
    time_end   date                   not null
);

-- drop table patient_journals;
create table patient_journals
(
    id         number(20, 0) generated by default as identity (start with 1 increment by 1 maxvalue 99999999999999999999 nocycle cache 20) primary key,
    patient_id number(20, 0)      not null references patients (id),
    ticket_id  number(20, 0)      not null references tickets (id),
    status     smallint default 0 not null
);

commit;