-- drop table users;
create table KOTLYAROV_DM.users
(
    id       number generated by default as identity (nocycle cache 20) primary key,
    name     varchar2(255)        not null,
    email    varchar2(255) unique not null,
    password varchar2(255)        not null
);

create table KOTLYAROV_DM.genders
(
    id   number generated by default as identity (nocycle cache 20) primary key,
    name varchar2(255) not null
);

-- drop table patients;
create table KOTLYAROV_DM.patients
(
    id         number generated by default as identity (nocycle cache 20) primary key,
    user_id    number        not null references users (id),
    first_name varchar2(255) not null,
    last_name  varchar2(255) not null,
    patronymic varchar2(255) null,
    birthdate  date          not null,
    gender_id  number        not null references genders (id),
    phone      number        null,
    area       varchar2(255) not null
);

-- drop table patient_documents;
create table KOTLYAROV_DM.patient_documents
(
    id         number generated by default as identity (nocycle cache 20) primary key,
    name       varchar2(255) not null,
    patient_id number        not null references patients (id),
    content    blob          null
);

-- drop table regions;
create table KOTLYAROV_DM.regions
(
    id   number generated by default as identity (nocycle cache 20) primary key,
    name varchar2(255) not null,
    code number(3, 0)  not null,

    constraint regions_name_code_unique unique (name, code)
);

-- drop table towns;
create table KOTLYAROV_DM.towns
(
    id        number generated by default as identity (nocycle cache 20) primary key,
    name      varchar2(255) unique not null,
    region_id number               not null references regions (id)
);

-- drop table organizations;
create table KOTLYAROV_DM.organizations
(
    id      number generated by default as identity (nocycle cache 20) primary key,
    name    varchar2(255) not null,
    town_id number        not null references towns (id)
);

create table KOTLYAROV_DM.hospital_types
(
    id   number generated by default as identity (nocycle cache 20) primary key,
    name varchar2(255) not null
);

create table KOTLYAROV_DM.week_days
(
    id   number(1, 0) primary key,
    name varchar2(255)
);

-- drop table hospitals;
create table KOTLYAROV_DM.hospitals
(
    id              number generated by default as identity (nocycle cache 20) primary key,
    deleted_at      date               null,
    name            varchar2(255)      not null,
    organization_id number             not null references organizations (id),
    status          smallint default 0 not null,
    type_id         number             not null references hospital_types (id)
);

create table KOTLYAROV_DM.hospital_work_times
(
    id          number generated by default as identity (nocycle cache 20) primary key,
    week_day_id number(1) references week_days (id),
    hospital_id number references hospitals (id),
    begin_time  number(5, 0) null,
    end_time    number(5, 0) null,

    constraint hospital_work_times_week_day_id_hospital_id_unique unique (week_day_id, hospital_id)
);

-- drop table doctors;
create table KOTLYAROV_DM.doctors
(
    id          number generated by default as identity (nocycle cache 20) primary key,
    deleted_at  date          null,
    area        varchar2(255) not null,
    degree      varchar2(255) not null,
    hospital_id number        not null references hospitals (id)
);

create table KOTLYAROV_DM.age_groups
(
    id        number generated by default as identity (nocycle cache 20) primary key,
    name      varchar2(255)            null,
    age_begin number(3, 0) default 0   not null,
    age_end   number(3, 0) default 999 not null
);

-- drop table specialities;
create table KOTLYAROV_DM.specialities
(
    id           number generated by default as identity (nocycle cache 20) primary key,
    deleted_at   date   null,
    age_group_id number not null references age_groups (id),
    gender_id    number not null references genders (id)
);

-- drop table doctor_specialty;
create table KOTLYAROV_DM.doctor_specialty
(
    speciality_id number not null references specialities (id),
    doctor_id     number not null references doctors (id),

    constraint doctor_specialty_speciality_id_doctor_id_unique primary key (speciality_id, doctor_id)
);

create table KOTLYAROV_DM.speciality_gender
(
    speciality_id number not null references specialities (id),
    gender_id     number not null references genders (id),

    constraint speciality_gender_speciality_id_gender_id_unique primary key (speciality_id, gender_id)
);

-- drop table tickets;
create table KOTLYAROV_DM.tickets
(
    id         number generated by default as identity (nocycle cache 20) primary key,
    doctor_id  number                 not null references doctors (id),
    closed     number(1, 0) default 0 not null,
    time_begin date                   not null,
    time_end   date                   not null
);

-- drop table patient_journals;
create table KOTLYAROV_DM.patient_journals
(
    id         number generated by default as identity (nocycle cache 20) primary key,
    patient_id number             not null references patients (id),
    ticket_id  number             not null references tickets (id),
    status     smallint default 0 not null
);

commit;