-- drop table KOTLYAROV_DM.users;
create table KOTLYAROV_DM.users
(
    id       number generated by default as identity (nocycle cache 20) primary key,
    name     varchar2(255)        not null,
    email    varchar2(255) unique not null,
    password varchar2(255)        not null
);

-- drop table KOTLYAROV_DM.genders;
create table KOTLYAROV_DM.genders
(
    id   number generated by default as identity (nocycle cache 20) primary key,
    name varchar2(255) not null
);

-- drop table KOTLYAROV_DM.patients;
create table KOTLYAROV_DM.patients
(
    id         number generated by default as identity (nocycle cache 20) primary key,
    id_user    number        not null references KOTLYAROV_DM.users (id),
    first_name varchar2(255) not null,
    last_name  varchar2(255) not null,
    patronymic varchar2(255) null,
    birthdate  date          not null,
    id_gender  number        not null references KOTLYAROV_DM.genders (id),
    phone      number        null,
    area       varchar2(255) not null
);

-- drop table KOTLYAROV_DM.patient_documents;
create table KOTLYAROV_DM.document_types
(
    id        number generated by default as identity (nocycle cache 20) primary key,
    type_name varchar2(255) unique not null
);

-- drop table KOTLYAROV_DM.patient_documents;
create table KOTLYAROV_DM.patient_documents
(
    id               number generated by default as identity (nocycle cache 20) primary key,
    name             varchar2(255) not null,
    id_patient       number        not null references KOTLYAROV_DM.patients (id),
    file_name        varchar2(255) not null,
    content          blob          null,
    id_document_type number        not null references KOTLYAROV_DM.document_types (id)
);

-- drop table KOTLYAROV_DM.regions;
create table KOTLYAROV_DM.regions
(
    id   number generated by default as identity (nocycle cache 20) primary key,
    name varchar2(255) not null,
    code number(3, 0)  not null,

    constraint regions_name_code_unique unique (name, code)
);

-- drop table KOTLYAROV_DM.towns;
create table KOTLYAROV_DM.towns
(
    id        number generated by default as identity (nocycle cache 20) primary key,
    name      varchar2(255) unique not null,
    id_region number               not null references KOTLYAROV_DM.regions (id)
);

-- drop table KOTLYAROV_DM.organizations;
create table KOTLYAROV_DM.organizations
(
    id      number generated by default as identity (nocycle cache 20) primary key,
    name    varchar2(255) not null,
    id_town number        not null references KOTLYAROV_DM.towns (id)
);

-- drop table KOTLYAROV_DM.hospital_types;
create table KOTLYAROV_DM.hospital_types
(
    id   number generated by default as identity (nocycle cache 20) primary key,
    name varchar2(255) not null
);

-- drop table KOTLYAROV_DM.week_days;
create table KOTLYAROV_DM.week_days
(
    id   number(1, 0) primary key,
    name varchar2(255)
);

-- drop table KOTLYAROV_DM.hospitals;
create table KOTLYAROV_DM.hospitals
(
    id                      number generated by default as identity (nocycle cache 20) primary key,
    deleted_at              date               null,
    name                    varchar2(255)      not null,
    id_organization         number             not null references KOTLYAROV_DM.organizations (id),
    status                  smallint default 0 not null,
    id_type                 number             not null references KOTLYAROV_DM.hospital_types (id),
    id_integration_hospital number             null
);

create table KOTLYAROV_DM.hospital_work_times
(
    id          number generated by default as identity (nocycle cache 20) primary key,
    id_week_day number(1) references KOTLYAROV_DM.week_days (id),
    id_hospital number references KOTLYAROV_DM.hospitals (id),
    begin_time  varchar2(5) null,
    end_time    varchar2(5) null,

    constraint hospital_work_times_id_week_day_id_hospital_unique unique (id_week_day, id_hospital)
);

-- drop table KOTLYAROV_DM.doctors;
create table KOTLYAROV_DM.doctors
(
    id                    number generated by default as identity (nocycle cache 20) primary key,
    deleted_at            date          null,
    area                  varchar2(255) not null,
    degree                numeric       not null,
    qualification         varchar2(255) not null,
    salary                number        not null,
    id_hospital           number        not null references KOTLYAROV_DM.hospitals (id),
    id_integration_doctor number        null
);

-- drop table KOTLYAROV_DM.doctors_reviews;
create table KOTLYAROV_DM.doctors_reviews
(
    id        number generated by default as identity (nocycle cache 20) primary key,
    id_doctor number              not null references KOTLYAROV_DM.doctors (id),
    review    varchar2(4000)      not null,
    rate      number(1) default 0 not null
);

-- drop table KOTLYAROV_DM.age_groups;
create table KOTLYAROV_DM.age_groups
(
    id        number generated by default as identity (nocycle cache 20) primary key,
    name      varchar2(255)            null,
    age_begin number(3, 0) default 0   not null,
    age_end   number(3, 0) default 999 not null
);

-- drop table KOTLYAROV_DM.specialities;
create table KOTLYAROV_DM.specialities
(
    id                       number generated by default as identity (nocycle cache 20) primary key,
    deleted_at               date   null,
    id_age_group             number not null references KOTLYAROV_DM.age_groups (id),
    id_integration_specialty number null
);

-- drop table KOTLYAROV_DM.doctor_specialty;
create table KOTLYAROV_DM.doctor_specialty
(
    id            number generated by default as identity (nocycle cache 20) primary key,
    id_speciality number not null references KOTLYAROV_DM.specialities (id),
    id_doctor     number not null references KOTLYAROV_DM.doctors (id)
);

-- drop table KOTLYAROV_DM.speciality_gender;
create table KOTLYAROV_DM.speciality_gender
(
    id_speciality number not null references KOTLYAROV_DM.specialities (id),
    id_gender     number not null references KOTLYAROV_DM.genders (id),

    constraint speciality_id_gender_speciality_id_gender_primary primary key (id_speciality, id_gender)
);

-- drop table KOTLYAROV_DM.tickets;
create table KOTLYAROV_DM.tickets
(
    id                   number generated by default as identity (nocycle cache 20) primary key,
    id_doctor_speciality number                 not null references KOTLYAROV_DM.doctor_specialty (id),
    closed               number(1, 0) default 0 not null,
    time_begin           date                   not null,
    time_end             date                   not null
);

-- drop table KOTLYAROV_DM.patient_journals;
create table KOTLYAROV_DM.patient_journals
(
    id_patient number             not null references KOTLYAROV_DM.patients (id),
    id_ticket  number             not null references KOTLYAROV_DM.tickets (id),
    status     smallint default 0 not null,

    constraint patient_journals_id_patient_id_ticket_primary primary key (id_patient, id_ticket)
);

create table KOTLYAROV_DM.system_logs
(
    id          number generated by default as identity (nocycle cache 20) primary key,

    sh_user     varchar2(50) default user,
    created_at  date         default sysdate,
    object_name varchar2(200),
    log_type    varchar2(1000),
    params      varchar2(4000)
)
    -- настроить в ней секционирование
    -- по дате создания на ближайшие три месяца
    partition by range (created_at)
(
    partition part_1 values less than (to_date('01.12.2021 00:00', 'dd.mm.yyyy hh24:mi')),
    partition part_2 values less than (to_date('01.01.2022 00:00', 'dd.mm.yyyy hh24:mi')),
    partition part_3 values less than (to_date('01.02.2022 00:00', 'dd.mm.yyyy hh24:mi')),

    partition part_max values less than (maxvalue)
);

commit;